#Gathering facts example
#by default facts gather is enable..
#if we want we can disable it by(gather_facts: no)
---
- name: Disable manually gatherfacts 
  hosts: all
  become: yes
  gather_facts: no             #Gathering facts disable
  tasks:
    - name: Starting web server
      service: 
        name: apache2
        state: started

    - name: stoppig the web server
      service:
         name: apache2
         state: stopped

