#Gathering facts example
#by default facts gather is enable..
#if we want we can disable it by(gather_facts: no)
---
- name: Disable manually gatherfacts 
  hosts: all
  become: yes
  tasks:
    - name: Gathering facts disable task
      gather_facts: no

    - name: Starting web server
      service: 
        name: apache2
        state: started

