#my first play book
---
- name: This set up apache2 server
  hosts: all
  tasks:
    - name: I want to update packages
      apt: 
        update_cache: yes
        
    - name: I want to install apache2 package
      apt:
       - name: apache2
         state: present
    
    - name: I want to Check apache2 started or not
      service:
        - name: apache2
          state: started
