#my first play book
---
- name: This set up apache2 server
  hosts: all
  become: yes
  tasks:
    - name: I want to update packages
      apt: 
        update_cache: yes             #apt-get update
        
    - name: I want to install apache2 package
      apt:                            #apt-get install apache2
        name: apache2                
        state: present
    
    - name: I want to Check apache2 started or not
      service:                        #service apache2 start
        name: apache2
        state: started
