#in this playbook, I am gonna install the softwares based on ansible_os_family=="Debian"
#Using gather_facts information.
- hosts: all
  become: yes
  tasks: 
    - name: update cache for Ubuntu nodes
      apt: 
        update_cache: yes
      when: ansible_os_family=="Debian"

    - name: update cache for RedHat nodes
      yum:
        update_cache: yes
      when: ansible_os_family=="RedHat"

    - name: I want to install softwares for Ubuntu nodes only
      apt:
        name: apache2
        state: present
      when: ansible_os_family=="Debian"

    - name: I want to start the apache2 server in Ubuntu nodes only
      service:
        name: apache2
        state: started
      when: ansible_os_family=="Debian"  
      
    - name: I wanto to install httpd server in RedHat nodes only
      apt:
        name: httpd
        state: present
      when: ansible_os_family=="RedHat" 

    - name: I want to start httpd server in RedHat nodes only
      service:
        name: httpd
        state: started
      when: ansible_os_family=="RedHat"
